# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md


use_try_shorthand = true

# Nightly configurations
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
version = "Two"

